apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: central-suporte-homolog
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - suporte.oondemand.online
    - api.suporte.oondemand.online
